// <auto-generated />
namespace FoodDeliverySystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedorderedproducts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedorderedproducts));
        
        string IMigrationMetadata.Id
        {
            get { return "201611040452283_added-ordered-products"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
